[PHP]
extension_dir = "C:\Users\calid\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"

extension=curl
extension=mbstring
extension=openssl
extension=fileinfo

error_reporting = E_ALL
display_errors = On
log_errors = On
error_log = "php_errors.log"

date.timezone = "America/Mexico_City"
